### ISSUE TITLE
wrong repo link in IDE library

### ISSUE THREAD

**Issue by FlorinAndrei** [arduino-libraries/Arduino_APDS9960#4]
If you install this library in the Arduino IDE, and click the More Info link, it sends you to a URL that does not exist:

https://github.com/arduino/Arduino_APDS9660

Instead, it should be:

https://github.com/arduino/Arduino_APDS9960

Please fix. Thanks!

**Comment by cmaglie** [comment]
This has been fixed since 1.0.1
