### ISSUE TITLE
Google Chrome anomaly with sample

### ISSUE THREAD

**Issue by baqwas** [arduino-libraries/Arduino_APDS9960#8]
Hello,

Apologies in advance since this may not be the most _productive_ place to submit this issue note. This novice will gladly post elsewhere upon suggestion.

My steps are:

- Rushed to practice the suggestion posted at https://twitter.com/arduino/status/1201957810084483074

- Compiled [sketch](https://t.co/brV3DsD5Q9?amp=1) (without any change) under **desktop IDE** after installing a [missing](https://github.com/arduino-libraries/Arduino_APDS9960) library 

- Uploaded sketch to Nano33 BLE board

- Launched Google Chrome (Version 78.0.3904.108 (Official Build) (64-bit)) under Ubuntu 19.10 (desktop) and received error message:

```
arduino.github.io says
Error: This browser doesn't support Web Bluetooth. Try using Chrome.
OK.
```

I receive the same error when building using the Arduino **Cloud IDE**.

Please provide some suggestion on correcting my mistake with any recommended workaround.
Kind regards.

**Comment by sandeepmistry** [comment]
Hi @baqwas,

Could you please "move" this issue to the following Github project: https://github.com/arduino/arduinoai

**Comment by baqwas** [comment]
Moving issue to suggested link at the request of the principal. Rgds.
